[package]
name = "xlite"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
calamine = "0.18.0"
nom = "7.1.0"

[dev-dependencies]
rusqlite = { version = "0.27.0", features = ["bundled", "load_extension"] }
